#服务基本信息配置
spring:
  sleuth:
    sampler:
      probability: 1
  #服务名称
  application:
    name: quanty-cloud-gateway
  zipkin:
  #默认sleuth向zipkin发送消息的方式就是web，可以修改成kafka,rabbitmq
#    sender:
#      type: web
    base-url: http://localhost:9411
    enabled: true
  cloud:
    nacos:
      #配置 nacos和 sentinel 地址
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      routes:
      - id: quanty-cloud-service-zk
        uri: lb://quanty-cloud-service-zk
        order: 8000
        predicates:
            ## 转发地址格式为 /api/zkservice/**，/api/zkservice/ 部分会被下面的过滤器给截取掉
        - Path=/api/zkservice/**
        filters:
            ## 截取路径位数
        - StripPrefix=2
logging:
  level:
    # log 级别
    org.springframework.cloud.gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false

server:
  port: 8300

